CREATE TABLE "product_collections" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" varchar(80) NOT NULL,
	"label" varchar(120) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_collections_key_unique" UNIQUE("key"),
	CONSTRAINT "product_collections_label_unique" UNIQUE("label")
);
--> statement-breakpoint
CREATE TABLE "product_collection_attribute_values" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"collection_attribute_id" uuid NOT NULL,
	"value" varchar(160) NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_collection_attribute_values_collection_attribute_id_value_unique" UNIQUE("collection_attribute_id","value")
);
--> statement-breakpoint
CREATE TABLE "product_collection_attributes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"collection_id" uuid NOT NULL,
	"attribute_key" varchar(80) NOT NULL,
	"label" varchar(120) NOT NULL,
	"data_type" varchar(30) DEFAULT 'text' NOT NULL,
	"unit" varchar(30),
	"multi_value" boolean DEFAULT false NOT NULL,
	"required" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_collection_attributes_collection_id_attribute_key_unique" UNIQUE("collection_id","attribute_key")
);
--> statement-breakpoint
ALTER TABLE "product_collection_attribute_values" ADD CONSTRAINT "product_collection_attribute_values_collection_attribute_id_product_collection_attributes_id_fk" FOREIGN KEY ("collection_attribute_id") REFERENCES "public"."product_collection_attributes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_collection_attributes" ADD CONSTRAINT "product_collection_attributes_collection_id_product_collections_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."product_collections"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "product_collections" ("key", "label")
VALUES
  ('cases', 'Cases'),
  ('desktops', 'Desktops'),
  ('displays', 'Displays'),
  ('input-devices', 'Input Devices'),
  ('laptops', 'Laptops'),
  ('lifestyle', 'Lifestyle'),
  ('tablets', 'Tablets')
ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_collection_attributes"
  ("collection_id", "attribute_key", "label", "data_type", "unit", "multi_value", "required", "sort_order")
SELECT c.id, a.attribute_key, a.label, a.data_type, a.unit, a.multi_value, a.required, a.sort_order
FROM (VALUES
  ('laptops', 'brand', 'Brand', 'enum', null, false, true, 10),
  ('laptops', 'model', 'Model', 'enum', null, false, true, 20),
  ('laptops', 'category', 'Category', 'enum', null, false, true, 30),
  ('laptops', 'series', 'Series', 'enum', null, false, false, 40),
  ('laptops', 'price', 'Price', 'enum', 'EUR', false, false, 50),
  ('laptops', 'discount', 'Discount', 'enum', '%', false, false, 60),
  ('laptops', 'screen_size', 'Screen Size', 'enum', 'inch', false, false, 70),
  ('laptops', 'resolution', 'Resolution', 'enum', null, false, false, 75),
  ('laptops', 'screen_resolution', 'Screen Resolution', 'enum', null, false, false, 80),
  ('laptops', 'processor', 'Processor', 'enum', null, false, false, 125),
  ('laptops', 'screen_type', 'Screen Type', 'enum', null, false, false, 90),
  ('laptops', 'refresh_rate', 'Refresh Rate', 'enum', 'Hz', false, false, 100),
  ('laptops', 'touchscreen', 'Touchscreen', 'enum', null, false, false, 110),
  ('laptops', 'processor_brand', 'Processor Brand', 'enum', null, false, false, 120),
  ('laptops', 'processor_model', 'Processor Model', 'enum', null, false, false, 130),
  ('laptops', 'processor_generation', 'Processor Generation', 'enum', null, false, false, 140),
  ('laptops', 'processor_cores', 'Processor Cores', 'enum', 'cores', false, false, 150),
  ('laptops', 'gpu_brand', 'GPU Brand', 'enum', null, false, false, 160),
  ('laptops', 'gpu', 'GPU', 'enum', null, false, false, 165),
  ('laptops', 'gpu_model', 'GPU Model', 'enum', null, false, false, 170),
  ('laptops', 'ram', 'RAM', 'enum', 'GB', false, false, 180),
  ('laptops', 'ram_type', 'RAM Type', 'enum', null, false, false, 190),
  ('laptops', 'ram_max', 'Max RAM', 'enum', 'GB', false, false, 200),
  ('laptops', 'storage_type', 'Storage Type', 'enum', null, false, false, 210),
  ('laptops', 'storage', 'Storage', 'enum', null, false, false, 215),
  ('laptops', 'storage_capacity', 'Storage Capacity', 'enum', 'GB', false, false, 220),
  ('laptops', 'battery_capacity', 'Battery Capacity', 'enum', 'Wh', false, false, 230),
  ('laptops', 'battery_life', 'Battery Life', 'enum', 'hours', false, false, 240),
  ('laptops', 'weight', 'Weight', 'enum', 'kg', false, false, 250),
  ('laptops', 'dimensions', 'Dimensions Profile', 'enum', null, false, false, 260),
  ('laptops', 'wifi', 'Wi-Fi', 'enum', null, false, false, 270),
  ('laptops', 'bluetooth', 'Bluetooth', 'enum', null, false, false, 280),
  ('laptops', 'ports', 'Ports', 'enum', null, true, false, 290),
  ('laptops', 'operating_system', 'Operating System', 'enum', null, false, false, 300),
  ('laptops', 'color', 'Color', 'enum', null, false, false, 310),
  ('displays', 'brand', 'Brand', 'enum', null, false, true, 10),
  ('displays', 'model', 'Model', 'enum', null, false, true, 20),
  ('displays', 'category', 'Category', 'enum', null, false, true, 30),
  ('displays', 'series', 'Series', 'enum', null, false, false, 40),
  ('displays', 'price', 'Price', 'enum', 'EUR', false, false, 50),
  ('displays', 'discount', 'Discount', 'enum', '%', false, false, 60),
  ('displays', 'screen_size', 'Screen Size', 'enum', 'inch', false, false, 70),
  ('displays', 'resolution', 'Resolution', 'enum', null, false, false, 75),
  ('displays', 'screen_resolution', 'Screen Resolution', 'enum', null, false, false, 80),
  ('displays', 'panel_type', 'Panel Type', 'enum', null, false, false, 85),
  ('displays', 'screen_type', 'Panel Type', 'enum', null, false, false, 90),
  ('displays', 'refresh_rate', 'Refresh Rate', 'enum', 'Hz', false, false, 100),
  ('displays', 'touchscreen', 'Touchscreen', 'enum', null, false, false, 110),
  ('displays', 'response_time', 'Response Time', 'enum', 'ms', false, false, 120),
  ('displays', 'aspect_ratio', 'Aspect Ratio', 'enum', null, false, false, 130),
  ('displays', 'curved', 'Curved', 'enum', null, false, false, 140),
  ('displays', 'brightness', 'Brightness', 'enum', 'nits', false, false, 150),
  ('displays', 'contrast_ratio', 'Contrast Ratio', 'enum', null, false, false, 160),
  ('displays', 'hdr', 'HDR', 'enum', null, false, false, 170),
  ('displays', 'gsync_freesync', 'G-Sync / FreeSync', 'enum', null, false, false, 175),
  ('displays', 'color_gamut', 'Color Gamut', 'enum', null, false, false, 180),
  ('displays', 'adaptive_sync', 'Adaptive Sync', 'enum', null, false, false, 190),
  ('displays', 'ports', 'Ports', 'enum', null, true, false, 200),
  ('displays', 'speakers', 'Speakers', 'enum', null, false, false, 210),
  ('displays', 'vesa_mount', 'VESA Mount', 'enum', null, false, false, 220),
  ('displays', 'stand_adjustments', 'Stand Adjustments', 'enum', null, true, false, 230),
  ('displays', 'color', 'Color', 'enum', null, false, false, 240)
) AS a(collection_key, attribute_key, label, data_type, unit, multi_value, required, sort_order)
JOIN "product_collections" c ON c."key" = a.collection_key
ON CONFLICT ("collection_id", "attribute_key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_collection_attribute_values" ("collection_attribute_id", "value", "sort_order")
SELECT a.id, v.value, v.sort_order
FROM (VALUES
  ('laptops', 'brand', 'Acer', 10),
  ('laptops', 'brand', 'Predator', 20),
  ('laptops', 'model', 'Aspire 3', 10),
  ('laptops', 'model', 'Aspire 5', 20),
  ('laptops', 'model', 'Swift Go 14', 30),
  ('laptops', 'model', 'Swift X 14', 40),
  ('laptops', 'model', 'TravelMate P4', 50),
  ('laptops', 'model', 'Extensa 15', 60),
  ('laptops', 'model', 'Nitro V 15', 70),
  ('laptops', 'model', 'Nitro 16', 80),
  ('laptops', 'model', 'Predator Helios Neo 16', 90),
  ('laptops', 'model', 'Predator Helios 16', 100),
  ('laptops', 'model', 'Predator Triton 14', 110),
  ('laptops', 'category', 'Ultrabook', 10),
  ('laptops', 'category', 'Gaming Laptop', 20),
  ('laptops', 'category', 'Business Laptop', 30),
  ('laptops', 'category', 'Creator Laptop', 40),
  ('laptops', 'category', 'Everyday Laptop', 50),
  ('laptops', 'category', '2-in-1 Laptop', 60),
  ('laptops', 'series', 'Aspire', 10),
  ('laptops', 'series', 'Swift', 20),
  ('laptops', 'series', 'Nitro', 30),
  ('laptops', 'series', 'Predator Helios', 40),
  ('laptops', 'series', 'Predator Triton', 50),
  ('laptops', 'series', 'TravelMate', 60),
  ('laptops', 'series', 'Extensa', 70),
  ('laptops', 'price', '499-799', 10),
  ('laptops', 'price', '800-1199', 20),
  ('laptops', 'price', '1200-1699', 30),
  ('laptops', 'price', '1700-2499', 40),
  ('laptops', 'price', '2500+', 50),
  ('laptops', 'discount', '0', 10),
  ('laptops', 'discount', '5', 20),
  ('laptops', 'discount', '10', 30),
  ('laptops', 'discount', '15', 40),
  ('laptops', 'discount', '20', 50),
  ('laptops', 'discount', '25', 60),
  ('laptops', 'discount', '30', 70),
  ('laptops', 'screen_size', '13.3', 10),
  ('laptops', 'screen_size', '14', 20),
  ('laptops', 'screen_size', '15.6', 30),
  ('laptops', 'screen_size', '16', 40),
  ('laptops', 'screen_size', '17.3', 50),
  ('laptops', 'screen_size', '18', 60),
  ('laptops', 'resolution', '1920x1080', 10),
  ('laptops', 'resolution', '1920x1200', 20),
  ('laptops', 'resolution', '2560x1600', 30),
  ('laptops', 'resolution', '2880x1800', 40),
  ('laptops', 'resolution', '3840x2160', 50),
  ('laptops', 'screen_resolution', '1920x1080', 10),
  ('laptops', 'screen_resolution', '1920x1200', 20),
  ('laptops', 'screen_resolution', '2560x1440', 30),
  ('laptops', 'screen_resolution', '2560x1600', 40),
  ('laptops', 'screen_resolution', '2880x1800', 50),
  ('laptops', 'screen_resolution', '3840x2160', 60),
  ('laptops', 'screen_type', 'IPS', 10),
  ('laptops', 'screen_type', 'OLED', 20),
  ('laptops', 'screen_type', 'Mini LED', 30),
  ('laptops', 'refresh_rate', '60', 10),
  ('laptops', 'refresh_rate', '90', 20),
  ('laptops', 'refresh_rate', '120', 30),
  ('laptops', 'refresh_rate', '144', 40),
  ('laptops', 'refresh_rate', '165', 50),
  ('laptops', 'refresh_rate', '240', 60),
  ('laptops', 'touchscreen', 'No', 10),
  ('laptops', 'touchscreen', 'Yes', 20),
  ('laptops', 'processor_brand', 'Intel', 10),
  ('laptops', 'processor_brand', 'AMD', 20),
  ('laptops', 'processor_brand', 'Qualcomm', 30),
  ('laptops', 'processor_model', 'Intel Core i5', 10),
  ('laptops', 'processor_model', 'Intel Core i7', 20),
  ('laptops', 'processor_model', 'Intel Core i9', 30),
  ('laptops', 'processor_model', 'Intel Core Ultra 5', 40),
  ('laptops', 'processor_model', 'Intel Core Ultra 7', 50),
  ('laptops', 'processor_model', 'Intel Core Ultra 9', 60),
  ('laptops', 'processor_model', 'AMD Ryzen 5', 70),
  ('laptops', 'processor_model', 'AMD Ryzen 7', 80),
  ('laptops', 'processor_model', 'AMD Ryzen 9', 90),
  ('laptops', 'processor_model', 'Snapdragon X Elite', 100),
  ('laptops', 'processor', 'Intel Core i5', 10),
  ('laptops', 'processor', 'Intel Core i7', 20),
  ('laptops', 'processor', 'Intel Core i9', 30),
  ('laptops', 'processor', 'Intel Core Ultra 7', 40),
  ('laptops', 'processor', 'AMD Ryzen 5', 50),
  ('laptops', 'processor', 'AMD Ryzen 7', 60),
  ('laptops', 'processor', 'AMD Ryzen 9', 70),
  ('laptops', 'processor_generation', '12th Gen', 10),
  ('laptops', 'processor_generation', '13th Gen', 20),
  ('laptops', 'processor_generation', '14th Gen', 30),
  ('laptops', 'processor_generation', 'Core Ultra Series 1', 40),
  ('laptops', 'processor_generation', 'Core Ultra Series 2', 50),
  ('laptops', 'processor_generation', 'Ryzen 7000 Series', 60),
  ('laptops', 'processor_generation', 'Ryzen 8000 Series', 70),
  ('laptops', 'processor_generation', 'Ryzen 9000 Series', 80),
  ('laptops', 'processor_cores', '6', 10),
  ('laptops', 'processor_cores', '8', 20),
  ('laptops', 'processor_cores', '10', 30),
  ('laptops', 'processor_cores', '12', 40),
  ('laptops', 'processor_cores', '14', 50),
  ('laptops', 'processor_cores', '16', 60),
  ('laptops', 'processor_cores', '24', 70),
  ('laptops', 'gpu_brand', 'NVIDIA', 10),
  ('laptops', 'gpu_brand', 'AMD', 20),
  ('laptops', 'gpu_brand', 'Intel', 30),
  ('laptops', 'gpu', 'Intel Arc Graphics', 10),
  ('laptops', 'gpu', 'GeForce RTX 4050', 20),
  ('laptops', 'gpu', 'GeForce RTX 4060', 30),
  ('laptops', 'gpu', 'GeForce RTX 4070', 40),
  ('laptops', 'gpu', 'GeForce RTX 4080', 50),
  ('laptops', 'gpu', 'GeForce RTX 4090', 60),
  ('laptops', 'gpu_model', 'Intel Arc Graphics', 10),
  ('laptops', 'gpu_model', 'Radeon 780M', 20),
  ('laptops', 'gpu_model', 'GeForce RTX 4050', 30),
  ('laptops', 'gpu_model', 'GeForce RTX 4060', 40),
  ('laptops', 'gpu_model', 'GeForce RTX 4070', 50),
  ('laptops', 'gpu_model', 'GeForce RTX 4080', 60),
  ('laptops', 'gpu_model', 'GeForce RTX 4090', 70),
  ('laptops', 'ram', '8', 10),
  ('laptops', 'ram', '16', 20),
  ('laptops', 'ram', '32', 30),
  ('laptops', 'ram', '64', 40),
  ('laptops', 'ram_type', 'DDR4', 10),
  ('laptops', 'ram_type', 'DDR5', 20),
  ('laptops', 'ram_type', 'LPDDR5', 30),
  ('laptops', 'ram_type', 'LPDDR5X', 40),
  ('laptops', 'ram_max', '16', 10),
  ('laptops', 'ram_max', '32', 20),
  ('laptops', 'ram_max', '64', 30),
  ('laptops', 'ram_max', '96', 40),
  ('laptops', 'storage_type', 'NVMe SSD', 10),
  ('laptops', 'storage_type', 'SATA SSD', 20),
  ('laptops', 'storage', '256GB SSD', 10),
  ('laptops', 'storage', '512GB SSD', 20),
  ('laptops', 'storage', '1TB SSD', 30),
  ('laptops', 'storage', '2TB SSD', 40),
  ('laptops', 'storage', '4TB SSD', 50),
  ('laptops', 'storage_capacity', '256', 10),
  ('laptops', 'storage_capacity', '512', 20),
  ('laptops', 'storage_capacity', '1000', 30),
  ('laptops', 'storage_capacity', '2000', 40),
  ('laptops', 'storage_capacity', '4000', 50),
  ('laptops', 'battery_capacity', '48', 10),
  ('laptops', 'battery_capacity', '57', 20),
  ('laptops', 'battery_capacity', '65', 30),
  ('laptops', 'battery_capacity', '76', 40),
  ('laptops', 'battery_capacity', '90', 50),
  ('laptops', 'battery_life', '6', 10),
  ('laptops', 'battery_life', '8', 20),
  ('laptops', 'battery_life', '10', 30),
  ('laptops', 'battery_life', '12', 40),
  ('laptops', 'battery_life', '14', 50),
  ('laptops', 'weight', '<1.4', 10),
  ('laptops', 'weight', '1.4-1.8', 20),
  ('laptops', 'weight', '1.8-2.3', 30),
  ('laptops', 'weight', '>2.3', 40),
  ('laptops', 'dimensions', 'Thin (<18 mm)', 10),
  ('laptops', 'dimensions', 'Standard (18-24 mm)', 20),
  ('laptops', 'dimensions', 'Performance (>24 mm)', 30),
  ('laptops', 'wifi', 'Wi-Fi 6', 10),
  ('laptops', 'wifi', 'Wi-Fi 6E', 20),
  ('laptops', 'wifi', 'Wi-Fi 7', 30),
  ('laptops', 'bluetooth', '5.1', 10),
  ('laptops', 'bluetooth', '5.2', 20),
  ('laptops', 'bluetooth', '5.3', 30),
  ('laptops', 'bluetooth', '5.4', 40),
  ('laptops', 'ports', 'USB-A', 10),
  ('laptops', 'ports', 'USB-C', 20),
  ('laptops', 'ports', 'Thunderbolt 4', 30),
  ('laptops', 'ports', 'HDMI 2.1', 40),
  ('laptops', 'ports', 'microSD', 50),
  ('laptops', 'ports', '3.5mm Audio Jack', 60),
  ('laptops', 'ports', 'RJ-45 Ethernet', 70),
  ('laptops', 'operating_system', 'Windows 11 Home', 10),
  ('laptops', 'operating_system', 'Windows 11 Pro', 20),
  ('laptops', 'operating_system', 'Linux', 30),
  ('laptops', 'operating_system', 'No OS', 40),
  ('laptops', 'color', 'Black', 10),
  ('laptops', 'color', 'White', 20),
  ('laptops', 'color', 'Silver', 30),
  ('laptops', 'color', 'Blue', 40),
  ('laptops', 'color', 'Gray', 50),
  ('displays', 'brand', 'Acer', 10),
  ('displays', 'brand', 'Predator', 20),
  ('displays', 'model', 'Nitro KG241Y', 10),
  ('displays', 'model', 'Nitro XV272U', 20),
  ('displays', 'model', 'Acer CB272', 30),
  ('displays', 'model', 'Predator XB273K', 40),
  ('displays', 'model', 'Predator X34 V', 50),
  ('displays', 'model', 'Predator X45', 60),
  ('displays', 'category', 'Gaming Monitor', 10),
  ('displays', 'category', 'Office Monitor', 20),
  ('displays', 'category', 'Creator Monitor', 30),
  ('displays', 'category', 'Ultrawide Monitor', 40),
  ('displays', 'series', 'Nitro', 10),
  ('displays', 'series', 'Acer CB', 20),
  ('displays', 'series', 'Predator XB', 30),
  ('displays', 'series', 'Predator X', 40),
  ('displays', 'price', '149-249', 10),
  ('displays', 'price', '250-399', 20),
  ('displays', 'price', '400-699', 30),
  ('displays', 'price', '700-1199', 40),
  ('displays', 'price', '1200+', 50),
  ('displays', 'discount', '0', 10),
  ('displays', 'discount', '5', 20),
  ('displays', 'discount', '10', 30),
  ('displays', 'discount', '15', 40),
  ('displays', 'discount', '20', 50),
  ('displays', 'screen_size', '23.8', 10),
  ('displays', 'screen_size', '24', 20),
  ('displays', 'screen_size', '27', 30),
  ('displays', 'screen_size', '31.5', 40),
  ('displays', 'screen_size', '34', 50),
  ('displays', 'screen_size', '45', 60),
  ('displays', 'resolution', '1920x1080', 10),
  ('displays', 'resolution', '2560x1440', 20),
  ('displays', 'resolution', '3440x1440', 30),
  ('displays', 'resolution', '3840x2160', 40),
  ('displays', 'screen_resolution', '1920x1080', 10),
  ('displays', 'screen_resolution', '2560x1440', 20),
  ('displays', 'screen_resolution', '3440x1440', 30),
  ('displays', 'screen_resolution', '3840x2160', 40),
  ('displays', 'screen_type', 'IPS', 10),
  ('displays', 'screen_type', 'VA', 20),
  ('displays', 'screen_type', 'OLED', 30),
  ('displays', 'screen_type', 'Mini LED', 40),
  ('displays', 'panel_type', 'IPS', 10),
  ('displays', 'panel_type', 'VA', 20),
  ('displays', 'panel_type', 'OLED', 30),
  ('displays', 'panel_type', 'Mini LED', 40),
  ('displays', 'refresh_rate', '60', 10),
  ('displays', 'refresh_rate', '75', 20),
  ('displays', 'refresh_rate', '120', 30),
  ('displays', 'refresh_rate', '144', 40),
  ('displays', 'refresh_rate', '165', 50),
  ('displays', 'refresh_rate', '180', 60),
  ('displays', 'refresh_rate', '240', 70),
  ('displays', 'touchscreen', 'No', 10),
  ('displays', 'touchscreen', 'Yes', 20),
  ('displays', 'response_time', '0.03', 10),
  ('displays', 'response_time', '0.5', 20),
  ('displays', 'response_time', '1', 30),
  ('displays', 'response_time', '2', 40),
  ('displays', 'response_time', '4', 50),
  ('displays', 'aspect_ratio', '16:9', 10),
  ('displays', 'aspect_ratio', '21:9', 20),
  ('displays', 'aspect_ratio', '32:9', 30),
  ('displays', 'curved', 'No', 10),
  ('displays', 'curved', '1000R', 20),
  ('displays', 'curved', '1500R', 30),
  ('displays', 'brightness', '250', 10),
  ('displays', 'brightness', '300', 20),
  ('displays', 'brightness', '400', 30),
  ('displays', 'brightness', '600', 40),
  ('displays', 'brightness', '1000', 50),
  ('displays', 'contrast_ratio', '1000:1', 10),
  ('displays', 'contrast_ratio', '3000:1', 20),
  ('displays', 'contrast_ratio', '1000000:1', 30),
  ('displays', 'hdr', 'None', 10),
  ('displays', 'hdr', 'HDR400', 20),
  ('displays', 'hdr', 'HDR600', 30),
  ('displays', 'hdr', 'HDR1000', 40),
  ('displays', 'gsync_freesync', 'None', 10),
  ('displays', 'gsync_freesync', 'G-SYNC Compatible', 20),
  ('displays', 'gsync_freesync', 'G-SYNC', 30),
  ('displays', 'gsync_freesync', 'FreeSync', 40),
  ('displays', 'gsync_freesync', 'FreeSync Premium', 50),
  ('displays', 'gsync_freesync', 'FreeSync Premium Pro', 60),
  ('displays', 'color_gamut', '95% sRGB', 10),
  ('displays', 'color_gamut', '99% sRGB', 20),
  ('displays', 'color_gamut', '95% DCI-P3', 30),
  ('displays', 'color_gamut', '99% Adobe RGB', 40),
  ('displays', 'adaptive_sync', 'None', 10),
  ('displays', 'adaptive_sync', 'AMD FreeSync', 20),
  ('displays', 'adaptive_sync', 'AMD FreeSync Premium', 30),
  ('displays', 'adaptive_sync', 'NVIDIA G-SYNC Compatible', 40),
  ('displays', 'ports', 'HDMI 2.0', 10),
  ('displays', 'ports', 'HDMI 2.1', 20),
  ('displays', 'ports', 'DisplayPort 1.4', 30),
  ('displays', 'ports', 'USB-C', 40),
  ('displays', 'ports', 'USB Hub', 50),
  ('displays', 'ports', '3.5mm Audio Out', 60),
  ('displays', 'speakers', 'No', 10),
  ('displays', 'speakers', '2x2W', 20),
  ('displays', 'speakers', '2x5W', 30),
  ('displays', 'vesa_mount', '75x75', 10),
  ('displays', 'vesa_mount', '100x100', 20),
  ('displays', 'stand_adjustments', 'Tilt', 10),
  ('displays', 'stand_adjustments', 'Swivel', 20),
  ('displays', 'stand_adjustments', 'Pivot', 30),
  ('displays', 'stand_adjustments', 'Height', 40),
  ('displays', 'color', 'Black', 10),
  ('displays', 'color', 'White', 20),
  ('displays', 'color', 'Silver', 30)
) AS v(collection_key, attribute_key, value, sort_order)
JOIN "product_collections" c ON c."key" = v.collection_key
JOIN "product_collection_attributes" a
  ON a."collection_id" = c.id
 AND a."attribute_key" = v.attribute_key
ON CONFLICT ("collection_attribute_id", "value") DO NOTHING;


